## Basic Functions

In [7]:
import numpy as np

In [8]:
array1 = np.array([[3,2,5],[4,5,6]])

In [9]:
print(type(array1))

<class 'numpy.ndarray'>


In [10]:
array1.shape

(2, 3)

In [11]:
array1.dtype

dtype('int32')

In [12]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [13]:
np.ones(6).dtype

dtype('float64')

In [14]:
np.empty((2,6)) #garbage value

array([[1.19537656e-311, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 1.25715837e-075],
       [1.84773919e-076, 7.16707088e-038, 2.25477946e+180,
        4.35291781e-061, 8.37822531e+169, 3.92588140e-033]])

In [15]:
array1

array([[3, 2, 5],
       [4, 5, 6]])

In [16]:
array1*array1

array([[ 9,  4, 25],
       [16, 25, 36]])

In [17]:
array1**array1

array([[   27,     4,  3125],
       [  256,  3125, 46656]], dtype=int32)

In [18]:
36**36

106387358923716524807713475752456393740167855629859291136

In [19]:
array2 = np.array([[3,2,5],[4,14,6]])

In [20]:
array2**array2

array([[         27,           4,        3125],
       [        256, -1282129920,       46656]], dtype=int32)

In [22]:
1/array2

array([[0.33333333, 0.5       , 0.2       ],
       [0.25      , 0.07142857, 0.16666667]])

## Slicing

In [23]:
array1

array([[3, 2, 5],
       [4, 5, 6]])

In [24]:
array1[2:3]

array([], shape=(0, 3), dtype=int32)

In [25]:
array3 = np.array([1,2,3,4,9,8,3,7])

In [26]:
arr = array3[4:6]

In [27]:
arr

array([9, 8])

In [28]:
arr[0] = 6

In [29]:
array3 # it will change 9 to 6 to avoid put .copy()

array([1, 2, 3, 4, 6, 8, 3, 7])

In [30]:
arr

array([6, 8])

In [31]:
array4 = np.array([1,2,3,7,1,9,4,7])

In [32]:
arr1 = array4[4:6].copy()

In [33]:
arr

array([6, 8])

In [34]:
arr1

array([1, 9])

In [35]:
arr1[0] = 5

In [36]:
array4

array([1, 2, 3, 7, 1, 9, 4, 7])

In [37]:
arr1

array([5, 9])