In [1]:
import numpy as np

In [3]:
a = np.arange(6)

In [4]:
a

array([0, 1, 2, 3, 4, 5])

In [9]:
b = np.array([4,6,9,8,6,9,5,6,5,5,2,5,4])


In [10]:
b.shape

(13,)

In [18]:
c = np.array([4,6,9,8,6,9,5,6,5,5,1,2,5,4])
#c = c.reshape(7,2)

In [17]:
c

array([[4, 6],
       [9, 8],
       [6, 9],
       [5, 6],
       [5, 5],
       [1, 2],
       [5, 4]])

In [19]:
c

array([4, 6, 9, 8, 6, 9, 5, 6, 5, 5, 1, 2, 5, 4])

In [20]:
np.argsort(c)

array([10, 11,  0, 13,  6,  8,  9, 12,  1,  4,  7,  3,  2,  5],
      dtype=int64)

In [22]:
np.argmin(c)

10

In [23]:
np.argmax(c)

2